### ISSUE TITLE
Enhanced retry epic

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#65]
- [x] Basic retry options - customise message failure retry delay - currently 1 seconds, enable/disable retry
- [ ] Retry max reached skip die or dlq or skip?  #196
- [x] Retry failure callback (instead or as well as DQL) implemented in #92
- [ ]  #242 
- [ ] DLQ #310

Strongly related to https://github.com/confluentinc/parallel-consumer/issues/34 - Monitor for progress and optionally shutdown (leave consumer group), skip message or send to DLQ #34

**Comment by astubbs** [comment]
BTW @ismarslomic , did you see `ParallelConsumerOptions#defaultMessageRetryDelay`? Do you think there should be more documentation around it?

I've added some docs - see https://github.com/confluentinc/parallel-consumer/pull/66/commits/917e4698a272a0764cdf6554237c6e819569db0a

**Comment by astubbs** [comment]
@radoslawtwardy -> https://github.com/confluentinc/parallel-consumer/issues/82 Custom retry delay duration from supplier function #82

**Comment by radoslawtwardy** [comment]
>  Custom retry delay duration from supplier function 
Possibility to define custom function will be great.

**Comment by astubbs** [comment]
> >  Custom retry delay duration from supplier function 
> 
> 
> 
> Possibility to define custom function will be great.

Great! Try out https://github.com/confluentinc/parallel-consumer/compare/master...astubbs:retry-delay-generator-func linked from the issue and let me know what you think of the api amd functionality.

**Comment by johnbyrnejb** [comment]
Closing Issue
